DeepL:
  deepl_auth_key: "DEEPLの認証キー"
OpenAI:
  openai_api_key: "OpenAIのAPIキー"
OBS:
  obs_host: "127.0.0.1"
  obs_port_no: 4444
  obs_password: "パスワード"
VOICEVOX:
  voicevox_host: "127.0.0.1"
  voicevox_prot_no: 50021
  voicevox_speaker_no: 8
ParlAI:
  parlai_host: "127.0.0.1"
  parlai_prot_no: 35496
PyAudio:
  # 標準スピーカー以外にも同時出力するかどうか
  pyaudio_second_output_enabled: false
  # 名前の一部でもいい
  pyaudio_second_output_host_api_name: "MME"
  pyaudio_second_output_device_name: "VB-Audio Virtual C"